/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFairtracksDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage.eINSTANCE);
		return result;
	}
	
}
