/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FairtracksDslProposalProvider extends AbstractFairtracksDslProposalProvider {
}
