/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFairtracksDslScopeProvider extends DelegatingScopeProvider {
}
