/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.provider;


import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel;

import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

/**
 * This is the item provider adapter for a {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FairtracksmodelItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FairtracksmodelItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addBoardLowerBoundPropertyDescriptor(object);
			addBoardUpperBoundPropertyDescriptor(object);
			addDistanceFromCornerPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Board Lower Bound feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addBoardLowerBoundPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Fairtracksmodel_boardLowerBound_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Fairtracksmodel_boardLowerBound_feature", "_UI_Fairtracksmodel_type"),
				 FairtracksDslPackage.Literals.FAIRTRACKSMODEL__BOARD_LOWER_BOUND,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Board Upper Bound feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addBoardUpperBoundPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Fairtracksmodel_boardUpperBound_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Fairtracksmodel_boardUpperBound_feature", "_UI_Fairtracksmodel_type"),
				 FairtracksDslPackage.Literals.FAIRTRACKSMODEL__BOARD_UPPER_BOUND,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Distance From Corner feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addDistanceFromCornerPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Fairtracksmodel_distanceFromCorner_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Fairtracksmodel_distanceFromCorner_feature", "_UI_Fairtracksmodel_type"),
				 FairtracksDslPackage.Literals.FAIRTRACKSMODEL__DISTANCE_FROM_CORNER,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS);
			childrenFeatures.add(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__OBJECT_DISTANCES);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns Fairtracksmodel.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/Fairtracksmodel"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		Fairtracksmodel fairtracksmodel = (Fairtracksmodel)object;
		return getString("_UI_Fairtracksmodel_type") + " " + fairtracksmodel.getBoardLowerBound();
	}
	

	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(Fairtracksmodel.class)) {
			case FairtracksDslPackage.FAIRTRACKSMODEL__BOARD_LOWER_BOUND:
			case FairtracksDslPackage.FAIRTRACKSMODEL__BOARD_UPPER_BOUND:
			case FairtracksDslPackage.FAIRTRACKSMODEL__DISTANCE_FROM_CORNER:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case FairtracksDslPackage.FAIRTRACKSMODEL__STATIC_OBJECTS:
			case FairtracksDslPackage.FAIRTRACKSMODEL__OBJECT_DISTANCES:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS,
				 FairtracksDslFactory.eINSTANCE.createFTStaticObject()));

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS,
				 FairtracksDslFactory.eINSTANCE.createFTPlayer()));

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS,
				 FairtracksDslFactory.eINSTANCE.createFTZone()));

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS,
				 FairtracksDslFactory.eINSTANCE.createFTObstacle()));

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__STATIC_OBJECTS,
				 FairtracksDslFactory.eINSTANCE.createFTZipline()));

		newChildDescriptors.add
			(createChildParameter
				(FairtracksDslPackage.Literals.FAIRTRACKSMODEL__OBJECT_DISTANCES,
				 FairtracksDslFactory.eINSTANCE.createFTDistance()));
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return FairtracksDslEditPlugin.INSTANCE;
	}

}
