/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FairtracksDslUiModule extends AbstractFairtracksDslUiModule {
}
