/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.impl;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FT Distance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl#getDistance <em>Distance</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl#getToObject <em>To Object</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FTDistanceImpl extends MinimalEObjectImpl.Container implements FTDistance
{
  /**
   * The default value of the '{@link #getDistance() <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistance()
   * @generated
   * @ordered
   */
  protected static final FTDistanceValue DISTANCE_EDEFAULT = FTDistanceValue.VERY_FAR_FROM;

  /**
   * The cached value of the '{@link #getDistance() <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistance()
   * @generated
   * @ordered
   */
  protected FTDistanceValue distance = DISTANCE_EDEFAULT;

  /**
   * The cached value of the '{@link #getToObject() <em>To Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToObject()
   * @generated
   * @ordered
   */
  protected FTObjectWithDistance toObject;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FTDistanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FairtracksDslPackage.Literals.FT_DISTANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FTDistanceValue getDistance()
  {
    return distance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDistance(FTDistanceValue newDistance)
  {
    FTDistanceValue oldDistance = distance;
    distance = newDistance == null ? DISTANCE_EDEFAULT : newDistance;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_DISTANCE__DISTANCE, oldDistance, distance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FTObjectWithDistance getToObject()
  {
    if (toObject != null && toObject.eIsProxy())
    {
      InternalEObject oldToObject = (InternalEObject)toObject;
      toObject = (FTObjectWithDistance)eResolveProxy(oldToObject);
      if (toObject != oldToObject)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FairtracksDslPackage.FT_DISTANCE__TO_OBJECT, oldToObject, toObject));
      }
    }
    return toObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FTObjectWithDistance basicGetToObject()
  {
    return toObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setToObject(FTObjectWithDistance newToObject)
  {
    FTObjectWithDistance oldToObject = toObject;
    toObject = newToObject;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_DISTANCE__TO_OBJECT, oldToObject, toObject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_DISTANCE__DISTANCE:
        return getDistance();
      case FairtracksDslPackage.FT_DISTANCE__TO_OBJECT:
        if (resolve) return getToObject();
        return basicGetToObject();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_DISTANCE__DISTANCE:
        setDistance((FTDistanceValue)newValue);
        return;
      case FairtracksDslPackage.FT_DISTANCE__TO_OBJECT:
        setToObject((FTObjectWithDistance)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_DISTANCE__DISTANCE:
        setDistance(DISTANCE_EDEFAULT);
        return;
      case FairtracksDslPackage.FT_DISTANCE__TO_OBJECT:
        setToObject((FTObjectWithDistance)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_DISTANCE__DISTANCE:
        return distance != DISTANCE_EDEFAULT;
      case FairtracksDslPackage.FT_DISTANCE__TO_OBJECT:
        return toObject != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (distance: ");
    result.append(distance);
    result.append(')');
    return result.toString();
  }

} //FTDistanceImpl
