/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.impl;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FT Real Coordinates</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl#getPosX <em>Pos X</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl#getPosY <em>Pos Y</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl#getSizeX <em>Size X</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl#getSizeY <em>Size Y</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FTRealCoordinatesImpl extends MinimalEObjectImpl.Container implements FTRealCoordinates
{
  /**
   * The default value of the '{@link #getPosX() <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosX()
   * @generated
   * @ordered
   */
  protected static final int POS_X_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPosX() <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosX()
   * @generated
   * @ordered
   */
  protected int posX = POS_X_EDEFAULT;

  /**
   * The default value of the '{@link #getPosY() <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosY()
   * @generated
   * @ordered
   */
  protected static final int POS_Y_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPosY() <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosY()
   * @generated
   * @ordered
   */
  protected int posY = POS_Y_EDEFAULT;

  /**
   * The default value of the '{@link #getSizeX() <em>Size X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeX()
   * @generated
   * @ordered
   */
  protected static final int SIZE_X_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeX() <em>Size X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeX()
   * @generated
   * @ordered
   */
  protected int sizeX = SIZE_X_EDEFAULT;

  /**
   * The default value of the '{@link #getSizeY() <em>Size Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeY()
   * @generated
   * @ordered
   */
  protected static final int SIZE_Y_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeY() <em>Size Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeY()
   * @generated
   * @ordered
   */
  protected int sizeY = SIZE_Y_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FTRealCoordinatesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FairtracksDslPackage.Literals.FT_REAL_COORDINATES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getPosX()
  {
    return posX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosX(int newPosX)
  {
    int oldPosX = posX;
    posX = newPosX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_REAL_COORDINATES__POS_X, oldPosX, posX));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getPosY()
  {
    return posY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosY(int newPosY)
  {
    int oldPosY = posY;
    posY = newPosY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_REAL_COORDINATES__POS_Y, oldPosY, posY));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSizeX()
  {
    return sizeX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSizeX(int newSizeX)
  {
    int oldSizeX = sizeX;
    sizeX = newSizeX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_X, oldSizeX, sizeX));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSizeY()
  {
    return sizeY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSizeY(int newSizeY)
  {
    int oldSizeY = sizeY;
    sizeY = newSizeY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_Y, oldSizeY, sizeY));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_X:
        return getPosX();
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_Y:
        return getPosY();
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_X:
        return getSizeX();
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_Y:
        return getSizeY();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_X:
        setPosX((Integer)newValue);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_Y:
        setPosY((Integer)newValue);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_X:
        setSizeX((Integer)newValue);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_Y:
        setSizeY((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_X:
        setPosX(POS_X_EDEFAULT);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_Y:
        setPosY(POS_Y_EDEFAULT);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_X:
        setSizeX(SIZE_X_EDEFAULT);
        return;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_Y:
        setSizeY(SIZE_Y_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_X:
        return posX != POS_X_EDEFAULT;
      case FairtracksDslPackage.FT_REAL_COORDINATES__POS_Y:
        return posY != POS_Y_EDEFAULT;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_X:
        return sizeX != SIZE_X_EDEFAULT;
      case FairtracksDslPackage.FT_REAL_COORDINATES__SIZE_Y:
        return sizeY != SIZE_Y_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (posX: ");
    result.append(posX);
    result.append(", posY: ");
    result.append(posY);
    result.append(", sizeX: ");
    result.append(sizeX);
    result.append(", sizeY: ");
    result.append(sizeY);
    result.append(')');
    return result.toString();
  }

} //FTRealCoordinatesImpl
