/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.ide


/**
 * Use this class to register ide components.
 */
class FairtracksDslIdeModule extends AbstractFairtracksDslIdeModule {
}
