/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FairtracksDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ca/mcgill/ecse/fairtracks/parser/antlr/internal/InternalFairtracksDsl.tokens");
	}
}
