/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.tests;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Fairtracksmodel</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FairtracksmodelTest extends TestCase {

	/**
	 * The fixture for this Fairtracksmodel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Fairtracksmodel fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FairtracksmodelTest.class);
	}

	/**
	 * Constructs a new Fairtracksmodel test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FairtracksmodelTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Fairtracksmodel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Fairtracksmodel fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Fairtracksmodel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Fairtracksmodel getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(FairtracksDslFactory.eINSTANCE.createFairtracksmodel());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FairtracksmodelTest
