/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.tests;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTHangingObs;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>FT Hanging Obs</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FTHangingObsTest extends FTObservationTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FTHangingObsTest.class);
	}

	/**
	 * Constructs a new FT Hanging Obs test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FTHangingObsTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this FT Hanging Obs test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected FTHangingObs getFixture() {
		return (FTHangingObs)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(FairtracksDslFactory.eINSTANCE.createFTHangingObs());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FTHangingObsTest
