/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.tests;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpObs;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>FT Pick Up Obs</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FTPickUpObsTest extends FTObservationTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FTPickUpObsTest.class);
	}

	/**
	 * Constructs a new FT Pick Up Obs test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FTPickUpObsTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this FT Pick Up Obs test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected FTPickUpObs getFixture() {
		return (FTPickUpObs)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(FairtracksDslFactory.eINSTANCE.createFTPickUpObs());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FTPickUpObsTest
