/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.tests;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>FT Pick Up Color Class</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FTPickUpColorClassTest extends TestCase {

	/**
	 * The fixture for this FT Pick Up Color Class test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FTPickUpColorClass fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FTPickUpColorClassTest.class);
	}

	/**
	 * Constructs a new FT Pick Up Color Class test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FTPickUpColorClassTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this FT Pick Up Color Class test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(FTPickUpColorClass fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this FT Pick Up Color Class test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FTPickUpColorClass getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(FairtracksDslFactory.eINSTANCE.createFTPickUpColorClass());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FTPickUpColorClassTest
