/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl.tests;

import ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneObs;
import ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>FT Zone Obs</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FTZoneObsTest extends FTObservationTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FTZoneObsTest.class);
	}

	/**
	 * Constructs a new FT Zone Obs test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FTZoneObsTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this FT Zone Obs test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected FTZoneObs getFixture() {
		return (FTZoneObs)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(FairtracksDslFactory.eINSTANCE.createFTZoneObs());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FTZoneObsTest
