/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslFactory
 * @model kind="package"
 * @generated
 */
public interface FairtracksDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fairtracksDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mcgill.ca/ecse/fairtracks/FairtracksDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fairtracksDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FairtracksDslPackage eINSTANCE = ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksmodelImpl <em>Fairtracksmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksmodelImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFairtracksmodel()
   * @generated
   */
  int FAIRTRACKSMODEL = 0;

  /**
   * The feature id for the '<em><b>Static Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIRTRACKSMODEL__STATIC_OBJECTS = 0;

  /**
   * The feature id for the '<em><b>Initial Distances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIRTRACKSMODEL__INITIAL_DISTANCES = 1;

  /**
   * The number of structural features of the '<em>Fairtracksmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIRTRACKSMODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStaticObjectImpl <em>FT Static Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStaticObjectImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTStaticObject()
   * @generated
   */
  int FT_STATIC_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATIC_OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATIC_OBJECT__SIZE = 1;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATIC_OBJECT__COORDINATES = 2;

  /**
   * The number of structural features of the '<em>FT Static Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATIC_OBJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObjectWithDistanceImpl <em>FT Object With Distance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObjectWithDistanceImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObjectWithDistance()
   * @generated
   */
  int FT_OBJECT_WITH_DISTANCE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBJECT_WITH_DISTANCE__NAME = FT_STATIC_OBJECT__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBJECT_WITH_DISTANCE__SIZE = FT_STATIC_OBJECT__SIZE;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBJECT_WITH_DISTANCE__COORDINATES = FT_STATIC_OBJECT__COORDINATES;

  /**
   * The feature id for the '<em><b>Distance Class</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBJECT_WITH_DISTANCE__DISTANCE_CLASS = FT_STATIC_OBJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>FT Object With Distance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT = FT_STATIC_OBJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPlayerImpl <em>FT Player</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPlayerImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPlayer()
   * @generated
   */
  int FT_PLAYER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__NAME = FT_OBJECT_WITH_DISTANCE__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__SIZE = FT_OBJECT_WITH_DISTANCE__SIZE;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__COORDINATES = FT_OBJECT_WITH_DISTANCE__COORDINATES;

  /**
   * The feature id for the '<em><b>Distance Class</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__DISTANCE_CLASS = FT_OBJECT_WITH_DISTANCE__DISTANCE_CLASS;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__ROLE = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initially Inside</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__INITIALLY_INSIDE = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Can Pick Up Object</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__CAN_PICK_UP_OBJECT = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Pick Up Color</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER__PICK_UP_COLOR = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>FT Player</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PLAYER_FEATURE_COUNT = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpColorClassImpl <em>FT Pick Up Color Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpColorClassImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpColorClass()
   * @generated
   */
  int FT_PICK_UP_COLOR_CLASS = 4;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PICK_UP_COLOR_CLASS__COLOR = 0;

  /**
   * The number of structural features of the '<em>FT Pick Up Color Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PICK_UP_COLOR_CLASS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneImpl <em>FT Zone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZone()
   * @generated
   */
  int FT_ZONE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__NAME = FT_OBJECT_WITH_DISTANCE__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__SIZE = FT_OBJECT_WITH_DISTANCE__SIZE;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__COORDINATES = FT_OBJECT_WITH_DISTANCE__COORDINATES;

  /**
   * The feature id for the '<em><b>Distance Class</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__DISTANCE_CLASS = FT_OBJECT_WITH_DISTANCE__DISTANCE_CLASS;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__TYPE = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Contains</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__CONTAINS = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Partially Overlaps</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__PARTIALLY_OVERLAPS = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Is Adjacent To</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__IS_ADJACENT_TO = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Disallowed Players</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE__DISALLOWED_PLAYERS = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>FT Zone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE_FEATURE_COUNT = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObstacleImpl <em>FT Obstacle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObstacleImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObstacle()
   * @generated
   */
  int FT_OBSTACLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__NAME = FT_OBJECT_WITH_DISTANCE__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__SIZE = FT_OBJECT_WITH_DISTANCE__SIZE;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__COORDINATES = FT_OBJECT_WITH_DISTANCE__COORDINATES;

  /**
   * The feature id for the '<em><b>Distance Class</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__DISTANCE_CLASS = FT_OBJECT_WITH_DISTANCE__DISTANCE_CLASS;

  /**
   * The feature id for the '<em><b>Is Moveable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__IS_MOVEABLE = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__COLOR = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Initially Inside</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__INITIALLY_INSIDE = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Disallowed Zones</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE__DISALLOWED_ZONES = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>FT Obstacle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSTACLE_FEATURE_COUNT = FT_OBJECT_WITH_DISTANCE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZiplineImpl <em>FT Zipline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZiplineImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZipline()
   * @generated
   */
  int FT_ZIPLINE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE__NAME = FT_STATIC_OBJECT__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE__SIZE = FT_STATIC_OBJECT__SIZE;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE__COORDINATES = FT_STATIC_OBJECT__COORDINATES;

  /**
   * The feature id for the '<em><b>Start Zone</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE__START_ZONE = FT_STATIC_OBJECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End Zone</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE__END_ZONE = FT_STATIC_OBJECT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>FT Zipline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZIPLINE_FEATURE_COUNT = FT_STATIC_OBJECT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl <em>FT Real Coordinates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTRealCoordinates()
   * @generated
   */
  int FT_REAL_COORDINATES = 8;

  /**
   * The feature id for the '<em><b>Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_REAL_COORDINATES__POS_X = 0;

  /**
   * The feature id for the '<em><b>Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_REAL_COORDINATES__POS_Y = 1;

  /**
   * The feature id for the '<em><b>Size X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_REAL_COORDINATES__SIZE_X = 2;

  /**
   * The feature id for the '<em><b>Size Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_REAL_COORDINATES__SIZE_Y = 3;

  /**
   * The number of structural features of the '<em>FT Real Coordinates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_REAL_COORDINATES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl <em>FT Distance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistance()
   * @generated
   */
  int FT_DISTANCE = 9;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE__DISTANCE = 0;

  /**
   * The feature id for the '<em><b>To Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE__TO_OBJECT = 1;

  /**
   * The number of structural features of the '<em>FT Distance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTTrajectoryImpl <em>FT Trajectory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTTrajectoryImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTTrajectory()
   * @generated
   */
  int FT_TRAJECTORY = 10;

  /**
   * The feature id for the '<em><b>Player</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_TRAJECTORY__PLAYER = 0;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_TRAJECTORY__STATES = 1;

  /**
   * The number of structural features of the '<em>FT Trajectory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_TRAJECTORY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStateImpl <em>FT State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStateImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTState()
   * @generated
   */
  int FT_STATE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE__POS_X = 1;

  /**
   * The feature id for the '<em><b>Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE__POS_Y = 2;

  /**
   * The feature id for the '<em><b>Observations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE__OBSERVATIONS = 3;

  /**
   * The feature id for the '<em><b>Next State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE__NEXT_STATE = 4;

  /**
   * The number of structural features of the '<em>FT State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_STATE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObservationImpl <em>FT Observation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObservationImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObservation()
   * @generated
   */
  int FT_OBSERVATION = 12;

  /**
   * The number of structural features of the '<em>FT Observation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_OBSERVATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceObsImpl <em>FT Distance Obs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceObsImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistanceObs()
   * @generated
   */
  int FT_DISTANCE_OBS = 13;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE_OBS__DISTANCE = FT_OBSERVATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE_OBS__OBJECT = FT_OBSERVATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>FT Distance Obs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_DISTANCE_OBS_FEATURE_COUNT = FT_OBSERVATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTHangingObsImpl <em>FT Hanging Obs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTHangingObsImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTHangingObs()
   * @generated
   */
  int FT_HANGING_OBS = 14;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_HANGING_OBS__OBJECT = FT_OBSERVATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>FT Hanging Obs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_HANGING_OBS_FEATURE_COUNT = FT_OBSERVATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpObsImpl <em>FT Pick Up Obs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpObsImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpObs()
   * @generated
   */
  int FT_PICK_UP_OBS = 15;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PICK_UP_OBS__OBJECT = FT_OBSERVATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>FT Pick Up Obs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_PICK_UP_OBS_FEATURE_COUNT = FT_OBSERVATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneObsImpl <em>FT Zone Obs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneObsImpl
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZoneObs()
   * @generated
   */
  int FT_ZONE_OBS = 16;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE_OBS__OBJECT = FT_OBSERVATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>FT Zone Obs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FT_ZONE_OBS_FEATURE_COUNT = FT_OBSERVATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor <em>FT Pick Up Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpColor()
   * @generated
   */
  int FT_PICK_UP_COLOR = 17;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole <em>FT Role</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTRole()
   * @generated
   */
  int FT_ROLE = 18;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType <em>FT Zone Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZoneType()
   * @generated
   */
  int FT_ZONE_TYPE = 19;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue <em>FT Distance Value</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistanceValue()
   * @generated
   */
  int FT_DISTANCE_VALUE = 20;

  /**
   * The meta object id for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize <em>FT Size</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTSize()
   * @generated
   */
  int FT_SIZE = 21;


  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel <em>Fairtracksmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fairtracksmodel</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel
   * @generated
   */
  EClass getFairtracksmodel();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getStaticObjects <em>Static Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Static Objects</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getStaticObjects()
   * @see #getFairtracksmodel()
   * @generated
   */
  EReference getFairtracksmodel_StaticObjects();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getInitialDistances <em>Initial Distances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initial Distances</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getInitialDistances()
   * @see #getFairtracksmodel()
   * @generated
   */
  EReference getFairtracksmodel_InitialDistances();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject <em>FT Static Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Static Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject
   * @generated
   */
  EClass getFTStaticObject();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getName()
   * @see #getFTStaticObject()
   * @generated
   */
  EAttribute getFTStaticObject_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getSize()
   * @see #getFTStaticObject()
   * @generated
   */
  EAttribute getFTStaticObject_Size();

  /**
   * Returns the meta object for the containment reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getCoordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coordinates</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getCoordinates()
   * @see #getFTStaticObject()
   * @generated
   */
  EReference getFTStaticObject_Coordinates();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance <em>FT Object With Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Object With Distance</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance
   * @generated
   */
  EClass getFTObjectWithDistance();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance#getDistanceClass <em>Distance Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Distance Class</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance#getDistanceClass()
   * @see #getFTObjectWithDistance()
   * @generated
   */
  EReference getFTObjectWithDistance_DistanceClass();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer <em>FT Player</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Player</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer
   * @generated
   */
  EClass getFTPlayer();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getRole()
   * @see #getFTPlayer()
   * @generated
   */
  EAttribute getFTPlayer_Role();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getInitiallyInside <em>Initially Inside</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initially Inside</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getInitiallyInside()
   * @see #getFTPlayer()
   * @generated
   */
  EReference getFTPlayer_InitiallyInside();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#isCanPickUpObject <em>Can Pick Up Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Can Pick Up Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#isCanPickUpObject()
   * @see #getFTPlayer()
   * @generated
   */
  EAttribute getFTPlayer_CanPickUpObject();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getPickUpColor <em>Pick Up Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pick Up Color</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer#getPickUpColor()
   * @see #getFTPlayer()
   * @generated
   */
  EReference getFTPlayer_PickUpColor();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass <em>FT Pick Up Color Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Pick Up Color Class</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass
   * @generated
   */
  EClass getFTPickUpColorClass();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass#getColor()
   * @see #getFTPickUpColorClass()
   * @generated
   */
  EAttribute getFTPickUpColorClass_Color();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone <em>FT Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Zone</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone
   * @generated
   */
  EClass getFTZone();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getType()
   * @see #getFTZone()
   * @generated
   */
  EAttribute getFTZone_Type();

  /**
   * Returns the meta object for the reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getContains <em>Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Contains</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getContains()
   * @see #getFTZone()
   * @generated
   */
  EReference getFTZone_Contains();

  /**
   * Returns the meta object for the reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getPartiallyOverlaps <em>Partially Overlaps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Partially Overlaps</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getPartiallyOverlaps()
   * @see #getFTZone()
   * @generated
   */
  EReference getFTZone_PartiallyOverlaps();

  /**
   * Returns the meta object for the reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getIsAdjacentTo <em>Is Adjacent To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Is Adjacent To</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getIsAdjacentTo()
   * @see #getFTZone()
   * @generated
   */
  EReference getFTZone_IsAdjacentTo();

  /**
   * Returns the meta object for the reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getDisallowedPlayers <em>Disallowed Players</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Disallowed Players</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getDisallowedPlayers()
   * @see #getFTZone()
   * @generated
   */
  EReference getFTZone_DisallowedPlayers();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle <em>FT Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Obstacle</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle
   * @generated
   */
  EClass getFTObstacle();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#isIsMoveable <em>Is Moveable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Moveable</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#isIsMoveable()
   * @see #getFTObstacle()
   * @generated
   */
  EAttribute getFTObstacle_IsMoveable();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getColor()
   * @see #getFTObstacle()
   * @generated
   */
  EAttribute getFTObstacle_Color();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getInitiallyInside <em>Initially Inside</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initially Inside</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getInitiallyInside()
   * @see #getFTObstacle()
   * @generated
   */
  EReference getFTObstacle_InitiallyInside();

  /**
   * Returns the meta object for the reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getDisallowedZones <em>Disallowed Zones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Disallowed Zones</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObstacle#getDisallowedZones()
   * @see #getFTObstacle()
   * @generated
   */
  EReference getFTObstacle_DisallowedZones();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline <em>FT Zipline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Zipline</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline
   * @generated
   */
  EClass getFTZipline();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getStartZone <em>Start Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Start Zone</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getStartZone()
   * @see #getFTZipline()
   * @generated
   */
  EReference getFTZipline_StartZone();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getEndZone <em>End Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>End Zone</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getEndZone()
   * @see #getFTZipline()
   * @generated
   */
  EReference getFTZipline_EndZone();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates <em>FT Real Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Real Coordinates</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates
   * @generated
   */
  EClass getFTRealCoordinates();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosX <em>Pos X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos X</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosX()
   * @see #getFTRealCoordinates()
   * @generated
   */
  EAttribute getFTRealCoordinates_PosX();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosY <em>Pos Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos Y</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosY()
   * @see #getFTRealCoordinates()
   * @generated
   */
  EAttribute getFTRealCoordinates_PosY();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeX <em>Size X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size X</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeX()
   * @see #getFTRealCoordinates()
   * @generated
   */
  EAttribute getFTRealCoordinates_SizeX();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeY <em>Size Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size Y</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeY()
   * @see #getFTRealCoordinates()
   * @generated
   */
  EAttribute getFTRealCoordinates_SizeY();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance <em>FT Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Distance</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance
   * @generated
   */
  EClass getFTDistance();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance#getDistance()
   * @see #getFTDistance()
   * @generated
   */
  EAttribute getFTDistance_Distance();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance#getToObject <em>To Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance#getToObject()
   * @see #getFTDistance()
   * @generated
   */
  EReference getFTDistance_ToObject();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory <em>FT Trajectory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Trajectory</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory
   * @generated
   */
  EClass getFTTrajectory();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory#getPlayer <em>Player</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Player</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory#getPlayer()
   * @see #getFTTrajectory()
   * @generated
   */
  EReference getFTTrajectory_Player();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTTrajectory#getStates()
   * @see #getFTTrajectory()
   * @generated
   */
  EReference getFTTrajectory_States();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState <em>FT State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT State</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState
   * @generated
   */
  EClass getFTState();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getName()
   * @see #getFTState()
   * @generated
   */
  EAttribute getFTState_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getPosX <em>Pos X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos X</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getPosX()
   * @see #getFTState()
   * @generated
   */
  EAttribute getFTState_PosX();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getPosY <em>Pos Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos Y</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getPosY()
   * @see #getFTState()
   * @generated
   */
  EAttribute getFTState_PosY();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getObservations <em>Observations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Observations</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getObservations()
   * @see #getFTState()
   * @generated
   */
  EReference getFTState_Observations();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getNextState <em>Next State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Next State</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTState#getNextState()
   * @see #getFTState()
   * @generated
   */
  EReference getFTState_NextState();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObservation <em>FT Observation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Observation</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObservation
   * @generated
   */
  EClass getFTObservation();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs <em>FT Distance Obs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Distance Obs</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs
   * @generated
   */
  EClass getFTDistanceObs();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs#getDistance()
   * @see #getFTDistanceObs()
   * @generated
   */
  EAttribute getFTDistanceObs_Distance();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceObs#getObject()
   * @see #getFTDistanceObs()
   * @generated
   */
  EReference getFTDistanceObs_Object();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTHangingObs <em>FT Hanging Obs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Hanging Obs</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTHangingObs
   * @generated
   */
  EClass getFTHangingObs();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTHangingObs#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTHangingObs#getObject()
   * @see #getFTHangingObs()
   * @generated
   */
  EReference getFTHangingObs_Object();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpObs <em>FT Pick Up Obs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Pick Up Obs</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpObs
   * @generated
   */
  EClass getFTPickUpObs();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpObs#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpObs#getObject()
   * @see #getFTPickUpObs()
   * @generated
   */
  EReference getFTPickUpObs_Object();

  /**
   * Returns the meta object for class '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneObs <em>FT Zone Obs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FT Zone Obs</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneObs
   * @generated
   */
  EClass getFTZoneObs();

  /**
   * Returns the meta object for the reference '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneObs#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneObs#getObject()
   * @see #getFTZoneObs()
   * @generated
   */
  EReference getFTZoneObs_Object();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor <em>FT Pick Up Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FT Pick Up Color</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor
   * @generated
   */
  EEnum getFTPickUpColor();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole <em>FT Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FT Role</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole
   * @generated
   */
  EEnum getFTRole();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType <em>FT Zone Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FT Zone Type</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType
   * @generated
   */
  EEnum getFTZoneType();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue <em>FT Distance Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FT Distance Value</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue
   * @generated
   */
  EEnum getFTDistanceValue();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize <em>FT Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FT Size</em>'.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize
   * @generated
   */
  EEnum getFTSize();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FairtracksDslFactory getFairtracksDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksmodelImpl <em>Fairtracksmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksmodelImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFairtracksmodel()
     * @generated
     */
    EClass FAIRTRACKSMODEL = eINSTANCE.getFairtracksmodel();

    /**
     * The meta object literal for the '<em><b>Static Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIRTRACKSMODEL__STATIC_OBJECTS = eINSTANCE.getFairtracksmodel_StaticObjects();

    /**
     * The meta object literal for the '<em><b>Initial Distances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIRTRACKSMODEL__INITIAL_DISTANCES = eINSTANCE.getFairtracksmodel_InitialDistances();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStaticObjectImpl <em>FT Static Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStaticObjectImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTStaticObject()
     * @generated
     */
    EClass FT_STATIC_OBJECT = eINSTANCE.getFTStaticObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_STATIC_OBJECT__NAME = eINSTANCE.getFTStaticObject_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_STATIC_OBJECT__SIZE = eINSTANCE.getFTStaticObject_Size();

    /**
     * The meta object literal for the '<em><b>Coordinates</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_STATIC_OBJECT__COORDINATES = eINSTANCE.getFTStaticObject_Coordinates();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObjectWithDistanceImpl <em>FT Object With Distance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObjectWithDistanceImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObjectWithDistance()
     * @generated
     */
    EClass FT_OBJECT_WITH_DISTANCE = eINSTANCE.getFTObjectWithDistance();

    /**
     * The meta object literal for the '<em><b>Distance Class</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_OBJECT_WITH_DISTANCE__DISTANCE_CLASS = eINSTANCE.getFTObjectWithDistance_DistanceClass();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPlayerImpl <em>FT Player</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPlayerImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPlayer()
     * @generated
     */
    EClass FT_PLAYER = eINSTANCE.getFTPlayer();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_PLAYER__ROLE = eINSTANCE.getFTPlayer_Role();

    /**
     * The meta object literal for the '<em><b>Initially Inside</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_PLAYER__INITIALLY_INSIDE = eINSTANCE.getFTPlayer_InitiallyInside();

    /**
     * The meta object literal for the '<em><b>Can Pick Up Object</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_PLAYER__CAN_PICK_UP_OBJECT = eINSTANCE.getFTPlayer_CanPickUpObject();

    /**
     * The meta object literal for the '<em><b>Pick Up Color</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_PLAYER__PICK_UP_COLOR = eINSTANCE.getFTPlayer_PickUpColor();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpColorClassImpl <em>FT Pick Up Color Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpColorClassImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpColorClass()
     * @generated
     */
    EClass FT_PICK_UP_COLOR_CLASS = eINSTANCE.getFTPickUpColorClass();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_PICK_UP_COLOR_CLASS__COLOR = eINSTANCE.getFTPickUpColorClass_Color();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneImpl <em>FT Zone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZone()
     * @generated
     */
    EClass FT_ZONE = eINSTANCE.getFTZone();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_ZONE__TYPE = eINSTANCE.getFTZone_Type();

    /**
     * The meta object literal for the '<em><b>Contains</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZONE__CONTAINS = eINSTANCE.getFTZone_Contains();

    /**
     * The meta object literal for the '<em><b>Partially Overlaps</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZONE__PARTIALLY_OVERLAPS = eINSTANCE.getFTZone_PartiallyOverlaps();

    /**
     * The meta object literal for the '<em><b>Is Adjacent To</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZONE__IS_ADJACENT_TO = eINSTANCE.getFTZone_IsAdjacentTo();

    /**
     * The meta object literal for the '<em><b>Disallowed Players</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZONE__DISALLOWED_PLAYERS = eINSTANCE.getFTZone_DisallowedPlayers();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObstacleImpl <em>FT Obstacle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObstacleImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObstacle()
     * @generated
     */
    EClass FT_OBSTACLE = eINSTANCE.getFTObstacle();

    /**
     * The meta object literal for the '<em><b>Is Moveable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_OBSTACLE__IS_MOVEABLE = eINSTANCE.getFTObstacle_IsMoveable();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_OBSTACLE__COLOR = eINSTANCE.getFTObstacle_Color();

    /**
     * The meta object literal for the '<em><b>Initially Inside</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_OBSTACLE__INITIALLY_INSIDE = eINSTANCE.getFTObstacle_InitiallyInside();

    /**
     * The meta object literal for the '<em><b>Disallowed Zones</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_OBSTACLE__DISALLOWED_ZONES = eINSTANCE.getFTObstacle_DisallowedZones();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZiplineImpl <em>FT Zipline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZiplineImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZipline()
     * @generated
     */
    EClass FT_ZIPLINE = eINSTANCE.getFTZipline();

    /**
     * The meta object literal for the '<em><b>Start Zone</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZIPLINE__START_ZONE = eINSTANCE.getFTZipline_StartZone();

    /**
     * The meta object literal for the '<em><b>End Zone</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZIPLINE__END_ZONE = eINSTANCE.getFTZipline_EndZone();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl <em>FT Real Coordinates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTRealCoordinatesImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTRealCoordinates()
     * @generated
     */
    EClass FT_REAL_COORDINATES = eINSTANCE.getFTRealCoordinates();

    /**
     * The meta object literal for the '<em><b>Pos X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_REAL_COORDINATES__POS_X = eINSTANCE.getFTRealCoordinates_PosX();

    /**
     * The meta object literal for the '<em><b>Pos Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_REAL_COORDINATES__POS_Y = eINSTANCE.getFTRealCoordinates_PosY();

    /**
     * The meta object literal for the '<em><b>Size X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_REAL_COORDINATES__SIZE_X = eINSTANCE.getFTRealCoordinates_SizeX();

    /**
     * The meta object literal for the '<em><b>Size Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_REAL_COORDINATES__SIZE_Y = eINSTANCE.getFTRealCoordinates_SizeY();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl <em>FT Distance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistance()
     * @generated
     */
    EClass FT_DISTANCE = eINSTANCE.getFTDistance();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_DISTANCE__DISTANCE = eINSTANCE.getFTDistance_Distance();

    /**
     * The meta object literal for the '<em><b>To Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_DISTANCE__TO_OBJECT = eINSTANCE.getFTDistance_ToObject();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTTrajectoryImpl <em>FT Trajectory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTTrajectoryImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTTrajectory()
     * @generated
     */
    EClass FT_TRAJECTORY = eINSTANCE.getFTTrajectory();

    /**
     * The meta object literal for the '<em><b>Player</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_TRAJECTORY__PLAYER = eINSTANCE.getFTTrajectory_Player();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_TRAJECTORY__STATES = eINSTANCE.getFTTrajectory_States();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStateImpl <em>FT State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTStateImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTState()
     * @generated
     */
    EClass FT_STATE = eINSTANCE.getFTState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_STATE__NAME = eINSTANCE.getFTState_Name();

    /**
     * The meta object literal for the '<em><b>Pos X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_STATE__POS_X = eINSTANCE.getFTState_PosX();

    /**
     * The meta object literal for the '<em><b>Pos Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_STATE__POS_Y = eINSTANCE.getFTState_PosY();

    /**
     * The meta object literal for the '<em><b>Observations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_STATE__OBSERVATIONS = eINSTANCE.getFTState_Observations();

    /**
     * The meta object literal for the '<em><b>Next State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_STATE__NEXT_STATE = eINSTANCE.getFTState_NextState();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObservationImpl <em>FT Observation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTObservationImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTObservation()
     * @generated
     */
    EClass FT_OBSERVATION = eINSTANCE.getFTObservation();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceObsImpl <em>FT Distance Obs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTDistanceObsImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistanceObs()
     * @generated
     */
    EClass FT_DISTANCE_OBS = eINSTANCE.getFTDistanceObs();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FT_DISTANCE_OBS__DISTANCE = eINSTANCE.getFTDistanceObs_Distance();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_DISTANCE_OBS__OBJECT = eINSTANCE.getFTDistanceObs_Object();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTHangingObsImpl <em>FT Hanging Obs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTHangingObsImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTHangingObs()
     * @generated
     */
    EClass FT_HANGING_OBS = eINSTANCE.getFTHangingObs();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_HANGING_OBS__OBJECT = eINSTANCE.getFTHangingObs_Object();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpObsImpl <em>FT Pick Up Obs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTPickUpObsImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpObs()
     * @generated
     */
    EClass FT_PICK_UP_OBS = eINSTANCE.getFTPickUpObs();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_PICK_UP_OBS__OBJECT = eINSTANCE.getFTPickUpObs_Object();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneObsImpl <em>FT Zone Obs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FTZoneObsImpl
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZoneObs()
     * @generated
     */
    EClass FT_ZONE_OBS = eINSTANCE.getFTZoneObs();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FT_ZONE_OBS__OBJECT = eINSTANCE.getFTZoneObs_Object();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor <em>FT Pick Up Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTPickUpColor()
     * @generated
     */
    EEnum FT_PICK_UP_COLOR = eINSTANCE.getFTPickUpColor();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole <em>FT Role</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRole
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTRole()
     * @generated
     */
    EEnum FT_ROLE = eINSTANCE.getFTRole();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType <em>FT Zone Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTZoneType()
     * @generated
     */
    EEnum FT_ZONE_TYPE = eINSTANCE.getFTZoneType();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue <em>FT Distance Value</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistanceValue
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTDistanceValue()
     * @generated
     */
    EEnum FT_DISTANCE_VALUE = eINSTANCE.getFTDistanceValue();

    /**
     * The meta object literal for the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize <em>FT Size</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize
     * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.impl.FairtracksDslPackageImpl#getFTSize()
     * @generated
     */
    EEnum FT_SIZE = eINSTANCE.getFTSize();

  }

} //FairtracksDslPackage
