/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fairtracksmodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getStaticObjects <em>Static Objects</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.Fairtracksmodel#getInitialDistances <em>Initial Distances</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFairtracksmodel()
 * @model
 * @generated
 */
public interface Fairtracksmodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Static Objects</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Static Objects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static Objects</em>' containment reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFairtracksmodel_StaticObjects()
   * @model containment="true"
   * @generated
   */
  EList<FTStaticObject> getStaticObjects();

  /**
   * Returns the value of the '<em><b>Initial Distances</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initial Distances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Distances</em>' containment reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFairtracksmodel_InitialDistances()
   * @model containment="true"
   * @generated
   */
  EList<FTDistance> getInitialDistances();

} // Fairtracksmodel
