/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>FT Distance Value</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTDistanceValue()
 * @model
 * @generated
 */
public enum FTDistanceValue implements Enumerator
{
  /**
   * The '<em><b>Very Far From</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VERY_FAR_FROM_VALUE
   * @generated
   * @ordered
   */
  VERY_FAR_FROM(0, "VeryFarFrom", "VeryFarFrom"),

  /**
   * The '<em><b>Far From</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FAR_FROM_VALUE
   * @generated
   * @ordered
   */
  FAR_FROM(1, "FarFrom", "FarFrom"),

  /**
   * The '<em><b>Close To</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLOSE_TO_VALUE
   * @generated
   * @ordered
   */
  CLOSE_TO(2, "CloseTo", "CloseTo"),

  /**
   * The '<em><b>Dangerously Close To</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DANGEROUSLY_CLOSE_TO_VALUE
   * @generated
   * @ordered
   */
  DANGEROUSLY_CLOSE_TO(3, "DangerouslyCloseTo", "DangerouslyCloseTo");

  /**
   * The '<em><b>Very Far From</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Very Far From</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #VERY_FAR_FROM
   * @model name="VeryFarFrom"
   * @generated
   * @ordered
   */
  public static final int VERY_FAR_FROM_VALUE = 0;

  /**
   * The '<em><b>Far From</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Far From</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FAR_FROM
   * @model name="FarFrom"
   * @generated
   * @ordered
   */
  public static final int FAR_FROM_VALUE = 1;

  /**
   * The '<em><b>Close To</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Close To</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CLOSE_TO
   * @model name="CloseTo"
   * @generated
   * @ordered
   */
  public static final int CLOSE_TO_VALUE = 2;

  /**
   * The '<em><b>Dangerously Close To</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Dangerously Close To</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DANGEROUSLY_CLOSE_TO
   * @model name="DangerouslyCloseTo"
   * @generated
   * @ordered
   */
  public static final int DANGEROUSLY_CLOSE_TO_VALUE = 3;

  /**
   * An array of all the '<em><b>FT Distance Value</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final FTDistanceValue[] VALUES_ARRAY =
    new FTDistanceValue[]
    {
      VERY_FAR_FROM,
      FAR_FROM,
      CLOSE_TO,
      DANGEROUSLY_CLOSE_TO,
    };

  /**
   * A public read-only list of all the '<em><b>FT Distance Value</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<FTDistanceValue> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>FT Distance Value</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FTDistanceValue get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FTDistanceValue result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>FT Distance Value</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FTDistanceValue getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FTDistanceValue result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>FT Distance Value</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FTDistanceValue get(int value)
  {
    switch (value)
    {
      case VERY_FAR_FROM_VALUE: return VERY_FAR_FROM;
      case FAR_FROM_VALUE: return FAR_FROM;
      case CLOSE_TO_VALUE: return CLOSE_TO;
      case DANGEROUSLY_CLOSE_TO_VALUE: return DANGEROUSLY_CLOSE_TO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private FTDistanceValue(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //FTDistanceValue
