/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Object With Distance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTObjectWithDistance#getDistanceClass <em>Distance Class</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTObjectWithDistance()
 * @model
 * @generated
 */
public interface FTObjectWithDistance extends FTStaticObject
{
  /**
   * Returns the value of the '<em><b>Distance Class</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTDistance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distance Class</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance Class</em>' containment reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTObjectWithDistance_DistanceClass()
   * @model containment="true"
   * @generated
   */
  EList<FTDistance> getDistanceClass();

} // FTObjectWithDistance
