/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Observation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTObservation()
 * @model
 * @generated
 */
public interface FTObservation extends EObject
{
} // FTObservation
