/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Pick Up Color Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTPickUpColorClass()
 * @model
 * @generated
 */
public interface FTPickUpColorClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor
   * @see #setColor(FTPickUpColor)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTPickUpColorClass_Color()
   * @model
   * @generated
   */
  FTPickUpColor getColor();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColorClass#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPickUpColor
   * @see #getColor()
   * @generated
   */
  void setColor(FTPickUpColor value);

} // FTPickUpColorClass
