/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Real Coordinates</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosX <em>Pos X</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosY <em>Pos Y</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeX <em>Size X</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeY <em>Size Y</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTRealCoordinates()
 * @model
 * @generated
 */
public interface FTRealCoordinates extends EObject
{
  /**
   * Returns the value of the '<em><b>Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos X</em>' attribute.
   * @see #setPosX(int)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTRealCoordinates_PosX()
   * @model
   * @generated
   */
  int getPosX();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosX <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos X</em>' attribute.
   * @see #getPosX()
   * @generated
   */
  void setPosX(int value);

  /**
   * Returns the value of the '<em><b>Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos Y</em>' attribute.
   * @see #setPosY(int)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTRealCoordinates_PosY()
   * @model
   * @generated
   */
  int getPosY();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getPosY <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos Y</em>' attribute.
   * @see #getPosY()
   * @generated
   */
  void setPosY(int value);

  /**
   * Returns the value of the '<em><b>Size X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size X</em>' attribute.
   * @see #setSizeX(int)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTRealCoordinates_SizeX()
   * @model
   * @generated
   */
  int getSizeX();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeX <em>Size X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size X</em>' attribute.
   * @see #getSizeX()
   * @generated
   */
  void setSizeX(int value);

  /**
   * Returns the value of the '<em><b>Size Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size Y</em>' attribute.
   * @see #setSizeY(int)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTRealCoordinates_SizeY()
   * @model
   * @generated
   */
  int getSizeY();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTRealCoordinates#getSizeY <em>Size Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size Y</em>' attribute.
   * @see #getSizeY()
   * @generated
   */
  void setSizeY(int value);

} // FTRealCoordinates
