/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Static Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getSize <em>Size</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getCoordinates <em>Coordinates</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTStaticObject()
 * @model
 * @generated
 */
public interface FTStaticObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTStaticObject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize
   * @see #setSize(FTSize)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTStaticObject_Size()
   * @model
   * @generated
   */
  FTSize getSize();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTSize
   * @see #getSize()
   * @generated
   */
  void setSize(FTSize value);

  /**
   * Returns the value of the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Coordinates</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinates</em>' containment reference.
   * @see #setCoordinates(FTRealCoordinates)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTStaticObject_Coordinates()
   * @model containment="true"
   * @generated
   */
  FTRealCoordinates getCoordinates();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTStaticObject#getCoordinates <em>Coordinates</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinates</em>' containment reference.
   * @see #getCoordinates()
   * @generated
   */
  void setCoordinates(FTRealCoordinates value);

} // FTStaticObject
