/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Zipline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getStartZone <em>Start Zone</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getEndZone <em>End Zone</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZipline()
 * @model
 * @generated
 */
public interface FTZipline extends FTStaticObject
{
  /**
   * Returns the value of the '<em><b>Start Zone</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start Zone</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Zone</em>' reference.
   * @see #setStartZone(FTZone)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZipline_StartZone()
   * @model
   * @generated
   */
  FTZone getStartZone();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getStartZone <em>Start Zone</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Zone</em>' reference.
   * @see #getStartZone()
   * @generated
   */
  void setStartZone(FTZone value);

  /**
   * Returns the value of the '<em><b>End Zone</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Zone</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Zone</em>' reference.
   * @see #setEndZone(FTZone)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZipline_EndZone()
   * @model
   * @generated
   */
  FTZone getEndZone();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZipline#getEndZone <em>End Zone</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Zone</em>' reference.
   * @see #getEndZone()
   * @generated
   */
  void setEndZone(FTZone value);

} // FTZipline
