/**
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks.fairtracksDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FT Zone</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getType <em>Type</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getContains <em>Contains</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getPartiallyOverlaps <em>Partially Overlaps</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getIsAdjacentTo <em>Is Adjacent To</em>}</li>
 *   <li>{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getDisallowedPlayers <em>Disallowed Players</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone()
 * @model
 * @generated
 */
public interface FTZone extends FTObjectWithDistance
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType
   * @see #setType(FTZoneType)
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone_Type()
   * @model
   * @generated
   */
  FTZoneType getType();

  /**
   * Sets the value of the '{@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZoneType
   * @see #getType()
   * @generated
   */
  void setType(FTZoneType value);

  /**
   * Returns the value of the '<em><b>Contains</b></em>' reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contains</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contains</em>' reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone_Contains()
   * @model
   * @generated
   */
  EList<FTZone> getContains();

  /**
   * Returns the value of the '<em><b>Partially Overlaps</b></em>' reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Partially Overlaps</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Partially Overlaps</em>' reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone_PartiallyOverlaps()
   * @model
   * @generated
   */
  EList<FTZone> getPartiallyOverlaps();

  /**
   * Returns the value of the '<em><b>Is Adjacent To</b></em>' reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTZone}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Adjacent To</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Adjacent To</em>' reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone_IsAdjacentTo()
   * @model
   * @generated
   */
  EList<FTZone> getIsAdjacentTo();

  /**
   * Returns the value of the '<em><b>Disallowed Players</b></em>' reference list.
   * The list contents are of type {@link ca.mcgill.ecse.fairtracks.fairtracksDsl.FTPlayer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Disallowed Players</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disallowed Players</em>' reference list.
   * @see ca.mcgill.ecse.fairtracks.fairtracksDsl.FairtracksDslPackage#getFTZone_DisallowedPlayers()
   * @model
   * @generated
   */
  EList<FTPlayer> getDisallowedPlayers();

} // FTZone
