/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FairtracksDslRuntimeModule extends AbstractFairtracksDslRuntimeModule {
}
