/*
 * generated by Xtext 2.12.0
 */
package ca.mcgill.ecse.fairtracks


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FairtracksDslStandaloneSetup extends FairtracksDslStandaloneSetupGenerated {

	def static void doSetup() {
		new FairtracksDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
